using Content.Client.UserInterface.Controls;
using Content.Shared._Floof.Bees;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Floof.Bees;


[GenerateTypedNameReferences]
public sealed partial class ApiaryWindow : FancyWindow
{
    private ISawmill _sawmill = default!;
    public event Action? OnBeeButton;
    public ApiaryWindow()
    {
        _sawmill = IoCManager.Resolve<ILogManager>().GetSawmill("Apiary");
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        BeeButton.OnPressed +=  _ =>
        {
            OnBeeButton?.Invoke();
        };
    }
    public void UpdateState(ApiaryUserInterfaceState state)
    {
        _sawmill.Log(LogLevel.Info, state.Progress+"");
        FuelBar.Value = state.Progress;
    }
}
